name: CI
on: push
jobs:

  test-8-2:
    name: "Tests on PHP 8.2"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          cp .github/workflows/.env .env
          make install-8.2
      - name: Run PHP tests
        run: make php-8.2-tests-ci
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: ./coverage.xml
          verbose: true

  test-8-3:
    name: "Tests on PHP 8.3"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          cp .github/workflows/.env .env
          make install-8.3
      - name: Run PHP tests
        run: make php-8.3-tests-ci

  code-validation:
    name: "Code validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          cp .github/workflows/.env .env
          make install
      - name: Run code validation
        run: make php-code-validation
